version: "3"

services:
    app:
        build: .
        container_name: my-heatmap
        restart: unless-stopped
        env_file: server/.env
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
        ports:
            - "8085:8085"
